apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "daily-scraper.fullname" . }}
  labels:
    app: {{ template "daily-scraper.name" . }}
    chart: {{ template "daily-scraper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  API_URL: {{ .Values.appConfig.apiUrl }}

